import "./global.css";
import NavBarController from "../components/NavBarController";
import QueryProvider from "../components/QueryProvider";
import { ThemeProvider } from "@org/shared-ui";
import AuthInitializer from "../components/AuthInitializer";

export const metadata = {
  title: "Welcome to admin-dashboard",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <AuthInitializer>
            <QueryProvider>
              <NavBarController />
              {children}
            </QueryProvider>
          </AuthInitializer>
        </ThemeProvider>
      </body>
    </html>
  );
}
